import type { RBACConfig } from "./types";

export const sampleConfig: RBACConfig = {
  permissions: [
    { id: "users.read", resource: "users", action: "read", description: "View user profiles" },
    { id: "users.create", resource: "users", action: "create", description: "Create new users" },
    { id: "users.update", resource: "users", action: "update", description: "Edit user details" },
    { id: "users.delete", resource: "users", action: "delete", description: "Delete users" },
    { id: "posts.read", resource: "posts", action: "read", description: "View posts" },
    { id: "posts.create", resource: "posts", action: "create", description: "Create posts" },
    { id: "posts.update", resource: "posts", action: "update", description: "Edit any post" },
    { id: "posts.delete", resource: "posts", action: "delete", description: "Delete any post" },
    { id: "posts.publish", resource: "posts", action: "publish", description: "Publish/unpublish posts" },
    { id: "settings.read", resource: "settings", action: "read", description: "View settings" },
    { id: "settings.update", resource: "settings", action: "update", description: "Modify settings" },
    { id: "audit.read", resource: "audit", action: "read", description: "View audit logs" },
    { id: "roles.manage", resource: "roles", action: "manage", description: "Manage roles and permissions" },
    { id: "billing.read", resource: "billing", action: "read", description: "View billing info" },
    { id: "billing.manage", resource: "billing", action: "manage", description: "Manage billing and plans" },
    { id: "api.keys", resource: "api", action: "keys", description: "Manage API keys" },
  ],
  roles: [
    {
      id: "viewer",
      name: "Viewer",
      description: "Read-only access to public resources",
      color: "#6b7280",
      permissions: ["users.read", "posts.read"],
    },
    {
      id: "editor",
      name: "Editor",
      description: "Can create and edit content",
      color: "#3b82f6",
      inherits: ["viewer"],
      permissions: ["posts.create", "posts.update"],
    },
    {
      id: "publisher",
      name: "Publisher",
      description: "Can publish and manage content",
      color: "#8b5cf6",
      inherits: ["editor"],
      permissions: ["posts.publish", "posts.delete"],
    },
    {
      id: "admin",
      name: "Admin",
      description: "Full access to most resources",
      color: "#f59e0b",
      inherits: ["publisher"],
      permissions: [
        "users.create", "users.update", "settings.read", "settings.update",
        "audit.read", "billing.read", "api.keys",
      ],
    },
    {
      id: "superadmin",
      name: "Super Admin",
      description: "Unrestricted access to everything",
      color: "#ef4444",
      inherits: ["admin"],
      permissions: ["users.delete", "roles.manage", "billing.manage"],
      isSystem: true,
    },
  ],
  policies: [
    {
      id: "policy-1",
      name: "Editor Self-Edit Only",
      description: "Editors can only edit their own posts",
      roles: ["editor"],
      permissions: ["posts.update"],
      conditions: [{ field: "post.authorId", operator: "eq", value: "{{userId}}" }],
      effect: "allow",
    },
    {
      id: "policy-2",
      name: "Admin Cannot Delete Self",
      description: "Admins cannot delete their own account",
      roles: ["admin"],
      permissions: ["users.delete"],
      conditions: [{ field: "target.id", operator: "eq", value: "{{userId}}" }],
      effect: "deny",
    },
  ],
};
